FROM golang:latest
RUN go get -u github.com/go-delve/delve/cmd/dlv
WORKDIR /app
#VOLUME "/root/.cache/go-build"

Copy go.mod .
Run go mod download
COPY . .
RUN go build -gcflags "all=-N -l"

CMD ["/go/bin/dlv", "--listen=:40000", "--headless=true", "--api-version=2", "exec", "./gateway"]