apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.database.name }}
  labels:
    {{- include "optox.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "optox.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "optox.selectorLabels" . | nindent 8 }}
        deployment: {{ .Values.database.name }}
    spec:
      volumes:
        - name: pv-storage
          persistentVolumeClaim:
            claimName: "{{ include "optox.fullname" . }}-pvc"
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "optox.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-postgres
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: pv-storage
              subPath: "fi"
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.database.image.repository }}:{{ .Values.database.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.database.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          ports:
            - name: database
              containerPort: 5432
              protocol: TCP
          env:
            - name: "POSTGRES_USER"
              valueFrom:
                secretKeyRef:
                  key:  postgresUsername
                  name: {{ .Release.Name }}-auth
            - name: "POSTGRES_PASSWORD"
              valueFrom:
                secretKeyRef:
                  key:  postgresPassword
                  name: {{ .Release.Name }}-auth
            - name: "POSTGRES_DB"
              value: {{ .Values.database.databaseName }}
            - name: "REGION"
              value: {{ .Values.region }}
            - name: "DEBUG"
              value: "{{ .Values.debug }}"
            {{ if hasKey .Values "webGuiCredentials" -}}
            - name: "WEB_GUI_USERNAME"
              valueFrom:
                secretKeyRef:
                  key:  webGuiUsername
                  name: {{ .Release.Name }}-gui-auth
            - name: "WEB_GUI_PASSWORD"
              valueFrom:
                secretKeyRef:
                  key:  webGuiPassword
                  name: {{ .Release.Name }}-gui-auth
            {{- end }}