apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.name }}
  labels:
    {{- include "optox.labels" . | nindent 4 }}
spec:
  type: {{ .Values.database.service.type }}
  ports:
    - port: {{ .Values.database.service.port }}
      targetPort: 5432
      protocol: TCP
      name: database
  selector:
    deployment: {{ .Values.database.name }}
