apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "optox.fullname" . }}-database-pvc
  labels:
    {{- include "optox.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.persistentVolume.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
