apiVersion: v1
kind: Service
metadata:
  name: {{ include "optox.fullname" . }}-frontend
  labels:
    {{- include "optox.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      port: 80
      protocol: TCP
      name: http
  selector:
    {{- include "optox.selectorLabels" . | nindent 4 }}
