{{ if hasKey .Values "webGuiCredentials" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-gui-auth
data:
  webGuiUsername: "{{ .Values.webGuiCredentials.username | b64enc }}"
  webGuiPassword: "{{ .Values.webGuiCredentials.password | b64enc }}"
{{- end }}