apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "optox.fullname" . }}-mediator
  labels:
    {{- include "optox.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "optox.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "optox.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "optox.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-mediator
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.mediator.image.repository }}:{{ .Values.mediator.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.mediator.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.mediator.service.port }}
              protocol: TCP
            {{ if .Values.debug -}}
            - name: debug
              containerPort: {{ .Values.mediator.debugPort }}
              protocol: TCP
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
