apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
  postgresUsername: "{{ .Values.database.credentials.postgresUsername | b64enc }}"
  postgresPassword: "{{ .Values.database.credentials.postgresPassword | b64enc }}"
  pgpoolAdminUsername: "{{ .Values.mediator.credentials.pgpoolAdminUsername | b64enc }}"
  pgpoolAdminPassword: "{{ .Values.mediator.credentials.pgpoolAdminPassword | b64enc }}"