apiVersion: v1
kind: Service
metadata:
  name: {{ include "optox.fullname" . }}-syncbackend
  labels:
    {{- include "optox.labels" . | nindent 4 }}
spec:
  type: {{ .Values.syncbackend.service.type }}
  ports:
    - port: {{ .Values.syncbackend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "optox.selectorLabels" . | nindent 4 }}
